backend:
  name: github
  repo: fredchanu/asso-simple
  branch: main

  
media_folder: "src/content/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Articles"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Date", name: "pubDate", widget: "datetime" }
      - { label: "Brouillon", name: "draft", widget: "boolean", default: false }
      - { label: "Contenu", name: "body", widget: "markdown" }
